### ISSUE TITLE
throttle 测试太过严谨

### ISSUE THREAD

**Issue by tommytroylin** [leftstick/fe-interview#2]
由于编写上的不同导致函数本身定义运行时间有细微差别，
再加上setTimeout本身的不确定性。导致正确的程序无法通过测试。

将答案中`if (typeof last === 'undefined') {`替换为简写的`if (!last) {`对程序本身毫无影响，但却无法通过3个测试。

即使使用`lodash`自身的`throttle`函数，也无法通过`Mocha`中精确到1ms的测试。

建议修改测试

**Comment by leftstick** [comment]
我来稍微回答一下：

1. `setTimeout`在我提供的测试中，所有值都是精确的，因为这里不光用了`mocha`，还利用[sinon.useFakeTimers](http://sinonjs.org/docs/#clock)来保证所有时间数据的精确性，否则测试用例就很难完成了。这也是一般当我们编写`unit test`时，如何保证时间操作正确性的重要手段。理论上讲，当你忽略`setTimeout`的不确定性(当精确值来思考)时，代码编写应该更简单才对
2. 换成`!last`的问题是，`last`可能为`0`。这主要还是因为`sinon`在fake时间时的起点不是真正的时间，而是`0`。但这个不会影响你的模块编写
3. `lodash`中的`throttle`拿到这里跑不过，很简单，我们的要求不一样。如果你仔细看过`lodash.throttle`文档的话，会发现这句话`Note: If leading and trailing options are true, func is invoked on the trailing edge of the timeout only if the throttled function is invoked more than once during the wait timeout. `，显然，我的测试题目并没有这个要求，我希望的是默认`leading`和`trailing`都为`true`，并且都执行。

最后，如果对照`lodash.throttle`的实现，你会发现，我提供的答案简直弱爆了(功能简陋)，究其原因，还是我在文章中提到的，本测试不是为了考死谁，而是希望候选人可以在测试用例的一步步提示下最终完成一个模块，并理解模块的基本运作方式。

**Comment by tommytroylin** [comment]
嗯。之前没有了解过sinon这个库。
感谢解答。受教了。
